### ISSUE TITLE
EPM API Endpoint Support

### ISSUE THREAD

**Issue by strick-j** [strick-j/CyberArk-APIs#9]
## Summary
Add support for EPM API Endpoints

### Basic example
NA

### Motivation
Support additional CyberArk API Endpoints.

**Comment by infamousjoeg** [comment]
Can I get a status update on this since you're a manager now?

**Comment by strick-j** [comment]
Coming soon

IN all seriousness you can see whats currently available by switching to the #9-epm-api-endpoint-support branch.
